config:
  aws:region: ap-southeast-2
  aws:allowedAccountIds:
    - '278728209435'
  firefox-extension:stage: prod
encryptionsalt: v1:jhBWhofXxwk=:v1:fmTpJdr/eEvll+cx:qfFZlbaKdb28qe1WMn8O0esYoRx0VA==
